<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0;net8.0</TargetFrameworks>
    <VersionPrefix>0.1.0</VersionPrefix>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/jakegough-jaytwo/jaytwo.LocalTime</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="jaytwo.LocalTime.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" Link="README.md" />
  </ItemGroup>
</Project>
